### ISSUE TITLE
Generate time functionality

### ISSUE THREAD

**Issue by dbeurle** [dbeurle/neon#140]
What's the purpose of `simulation["time"]["increments"]["initial"]`?  I'm refactoring the integration stuff and I'm confused at the role that this plays.  It seems to be stored inside the meshes and is only used for constructing boundary conditions.  Do you have any insight into this issue?

**Comment by shadisharba** [comment]
This is related to #114 and cyclic loading. Only `simulation["meshes"]` is passed to the mesh class. However, the generation of a cyclic loading requires early access to `simulation["time"]` to construct the whole load history. This can change depending on #114.

**Comment by dbeurle** [comment]
Okay - but it shouldn't need to be stored inside the class?  It could be passed as an argument until the timer view is implemented, or?

**Comment by shadisharba** [comment]
True, it's needed only in `allocate_boundary_conditions` and `allocate_displacement_boundary`.

**Comment by dbeurle** [comment]
Okay cool, then I'll change it for now until we have a better idea about #114.  Thanks :-)
