### ISSUE TITLE
Displacement controlled loading

### ISSUE THREAD

**Issue by dbeurle** [dbeurle/neon#19]
Displacement controlled loadings as they currently stand cause spurious plastic deformations in the elements connected to displacement nodes.  This is because the load is applied such that high localised strains are computed at the quadrature points.

It should be that a global or local linear solution is computed first as an approximation to the deformation state.

**Comment by dbeurle** [comment]
@shadialameddin  Can close this off now?

**Comment by shadisharba** [comment]
sure
