### ISSUE TITLE
Problem with the Tetrahedron4 and Triangle 3 element

### ISSUE THREAD

**Issue by shadisharba** [dbeurle/neon#30]
There is a problem with the Tetrahedron4 element. The displacement field is correct but all the other fields like stress or damage are NAN. Tetrahedron10 works perfectly as you can see in the last picture.

![linear_tet_displacement](https://user-images.githubusercontent.com/32618348/33380857-ade3a2fa-d51c-11e7-839c-feb1c902641c.png)
![linear_tet_stress](https://user-images.githubusercontent.com/32618348/33380858-ae07fc9a-d51c-11e7-9fe6-230d4e6a7d36.png)
![quadratic_tet](https://user-images.githubusercontent.com/32618348/33380859-ae232524-d51c-11e7-9c76-665b393d6f12.png)

**Comment by shadisharba** [comment]
I've just got that commit, thanks!
Aren't the values of all the shape functions at the quadrature point equal to 0.5?

**Comment by dbeurle** [comment]
Commit 07bc9deb5001f05960bf6ee8bc5b132f5e6b6e66 added tests for the elements.

**Comment by dbeurle** [comment]
If you evaluate the shape functions aren't they just 0.25 since N1 = r, N2 = s, N3 = t etc?  The quadrature point (single) is 0.25, 0.25, 0.25 ?

**Comment by shadisharba** [comment]
yes, my bad

**Comment by dbeurle** [comment]
So the extrapolation from the quadrature point to the nodal points should just be ones(4, 1)?  How does this look like for the model posted?  Is it *somewhere* close to the quadratic element?  I'd expect bad performance for simplex elements in the beam bending.

**Comment by shadisharba** [comment]
I think so. The results are not in contrast to the quadratic elements but it seems that the simplex elements are stiffer in this case. They underestimated the von Mises stresses for a bending problem, which is expected.
