### ISSUE TITLE
Implementation of cyclic loading

### ISSUE THREAD

**Issue by shadisharba** [dbeurle/neon#36]
If we want to run fatigue computations, it will be easier to have a "cyclic" option that changes the interpolation of the boundary conditions to fit a sinusoidal wave. An input example may look like:

"Cyclic" : "True",
"Amplitude" : [0.12,0.10], 
"Period" : [10,10],
"NumperOfCycles" : [2,1],
"Phase" : [0,0]

In this case "Times" and "Values" will be ignored and the respective values will be computed base on the given wave.

**Comment by shadisharba** [comment]
It may be interesting to have an extra input for the time discretisation 
"TimeStepsPerCycle"=[10,15]
The damage model is sensitive to the time discretisation. In this case, enforcing a specific time scheme rather than using the adaptive one may be more accurate for comparison reasons.

**Comment by dbeurle** [comment]
I think we can include this using a generator pattern.  Right now the base `Boundary` class handles the time and the scalar values.  It only needs to know what the how to interpolate between them if required.

```json
"Generator" : {
    "Type" : "Sinusoidal",
    "Amplitude" : [0.12, 0.10],
    "Period" : [10,10],
    "NumberOfCycles" : [2,1],
    "Phase" : [0,0]
}
```

What are you thoughts on this?  I'm torn at between generating these values on the fly or just evaluating them for all time points.  If we call everything a `generator`, then the default would be a `"Type" : "Static"` load like we currently have and the generator would store all the time points, otherwise it would generate them on the fly based on a given input time.

**Comment by shadisharba** [comment]
Yeah, generating all the values for all time points makes sense and it'll be useful for the LATIN implementation. On the other hand, when a time step is reduced, new values regarding the current step will have to be generated on the fly.

**Comment by shadisharba** [comment]
Now I have the  `times` and `values` generated in the `Boundary` class but that requires changing the calls from its subclasses depending on the generator type. What do you think about generating the required `times` and `values` in the `SimulationControl::parse()` function? Then, this is done once and the rest of the classes is not touched.

**Comment by dbeurle** [comment]
What do the changes look like in code?  We could generate these further up but I'm not sure if we want to expose `generate` methods further up the chain or simply a free function that generates the required `std::vector` for the `times` and `values` data.

**Comment by shadisharba** [comment]
Now, in `solid/femMesh`  I check `boundary["Generate"]["Type"] == "UserDefined"` and based on that I call different constructors which are added in `Dirichlet` and `Neumann` classes for example. The definition of `generate_sinusoidal(generate)` is in the `Boundary` class. In this case, I'll have to do the same for plane and thermal problems for example.

**Comment by dbeurle** [comment]
I understand now and this could get a little tedious to manage.  Could it instead be handled directly in the `Boundary` class?  This should be possible since the boundary value definitions are theory independent, and the only role that the `femMesh` should be performing is theory dependent (`traction` vs `pressure` etc).  That way the constructor call isn't being branched on inside the mesh and we hide the generation logic further down.

Do you think instead of passing in a `times` and `values` (or `loads`) into the boundary class, that a `"generate"` `json` object is passed and the `Boundary` class fills the containers as required?  That way we can test and implement generators without invoking a `femMesh` class.  How do the generators now work with individual dofs?

**Comment by shadisharba** [comment]
For sure, that's what I'm doing. I deleted what I previously added to `femMesh` by making all BC have a `generate` that may contain `times` and `values`. Now I have to modify the generator int the `Boundary` class to loop over the DOF.

**Comment by shadisharba** [comment]
I left the `femMesh` class to loop over the individual dofs and the call to the boundary constructor looks like
 `displacement_bcs[boundary_name].emplace_back(boundary_dofs, boundary["Generate"], std::string(name));`

**Comment by dbeurle** [comment]
Exactly - this looks good.

**Comment by dbeurle** [comment]
```json
"Name" : "VibratingBoundary",
"Type" : "Displacement",
"Time" : [0.0, 30],
"Components" : {
    "x" : [0.0, 0.08]
},
"Generate" : {
    "Type" : "Sinusoidal",
    "Amplitude" :{
         "x" : [0.12, 0.10]
    },
    "Period" : [10,10],
    "NumberOfCycles" : [2,1],
    "TimeStep" : [0.1,0.1],
    "Phase" : [0,0]
}
```

**Comment by shadisharba** [comment]
"Name" : "Clamped",
"Type" : "Displacement",
"Time" : [0.0, 30],

// default case
"x" : [0.0, 0.0],
"y" : [0.0, 0.0],
"z" : [0.0, 0.0],

// genetare case
"GenerateType" : "Sinusoidal",
"Amplitude" :{
    "x" : [0.0, 0.0]
},
"Period" : [10,10],
"Phase" : [0,0],
"NumberOfCycles" : [2,1]

// In this case, the generator uses the default time step and each boundary condition may follow any of the cases

// The generated values will be for one direction (dof) only, if we want to make it more flexible maybe we can read times and values from an input file (could be sth for the future), what do you think?

**Comment by dbeurle** [comment]
This is a good enough approach.  One small change on this is:

```json
"Name" : "Clamped",
"Type" : "Displacement",
"Time" : [0.0, 30],
// default case
"x" : [0.0, 0.0],
"y" : [0.0, 0.0],
"z" : [0.0, 0.0],
"Generate" : "Sinusoidal",
"Period" : [10,10],
"Phase" : [0,0],
"NumberOfCycles" : [2,1]
```

Where the amplitude is already given by the default case.  Thoughts?

**Comment by shadisharba** [comment]
you mean that x, y and z can be used as amplitude when the generator is activated?
By the default case, I mean "UserDefined". Do you agree on making all cases "UserDefined" if "Generate" is not given?

**Comment by dbeurle** [comment]
Yeah I think this is probably the simplest way.  Do you see anything bad?

If the Generate keyword isn't set then it will default to the previous boundary.  What's the point btw of the `"Values" : {` syntax?  Wouldn't it be easier to default to what I commented above without the `"Values" : {`.  I'm not sure anymore what that brings, or what I was thinking at the time.

**Comment by shadisharba** [comment]
I think the main limitation here is that one cannot make x and y, for example, have differently period or phase but this should be okay.

Currently, `"Values"` is used as a container and you can iterate over it to capture x, y and z. It can be removed but then you need to iterate over all the elements of the boundary condition to find the acceptable dof. Keep it?

**Comment by dbeurle** [comment]
I think we can just do a count on the json keys:  https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ae625a0647486edf2bb38c849ca67f934.html#ae625a0647486edf2bb38c849ca67f934

That way we can ditch the additional `"Values"` container.
