### ISSUE TITLE
Compile with debugging flag

### ISSUE THREAD

**Issue by shadisharba** [dbeurle/neon#41]
When the code is compiled with a debugging option, two tests fail `GeometryTest` and `MatrixSystemTest`.

**Comment by dbeurle** [comment]
Thanks - I'll add these to the automated tests and see if I can figure out why they are failing.

**Comment by dbeurle** [comment]
@shadialameddin See commit 52a2486.  Now it's broken, I'll put in the fixes over the weekend.  It seems like more than one test is broken.

**Comment by dbeurle** [comment]
So there are problems to do with the reshaping of the internal force computation.  It was probably optimised away (which it should be).  Now we have the copy back in and I will need to design the way this works to avoid these pesky memory allocations.

**Comment by dbeurle** [comment]
This is fixed by 59548ec and 70de08f.  Thanks for the report!
