### ISSUE TITLE
Killing off OpenMP

### ISSUE THREAD

**Issue by dbeurle** [dbeurle/neon#50]
OpenMP looks like crap.

We should move towards c++11 standard threads or something a compatible with this library.

The main multithreaded portions of the program are inside the internal variables update and the matrix assembly. We can swap out those manual for loops for something like:

https://www.threadingbuildingblocks.org/tutorial-intel-tbb-generic-parallel-algorithms

Got some thoughts on this Shadi?  We can still use an integer index which is handy when we have a lot of arrays to index into, and also means the code doesn't have to change too much.

**Comment by dbeurle** [comment]
You should be able to change the call
```cpp
Eigen::Matrix<double, n, n> Kdense = Eigen::MatrixXd::Zero(n, n); // global stiffness matrix
Eigen::Matrix<double, n_el, n_el> Ke = Eigen::MatrixXd::Ones(n_el, n_el); // elemental stiffness
```
to
```cpp
Eigen::MatrixXd Kdense = Eigen::MatrixXd::Zero(n, n); // global stiffness matrix
Eigen::MatrixXd Ke = Eigen::MatrixXd::Ones(n_el, n_el); // elemental stiffness

#pragma omp declare reduction(+ : Eigen::MatrixXd : omp_out =  omp_out + omp_in) \
                initializer(omp_priv=Eigen::MatrixXd::Zero(n, n))
```
Then the matrices are stored on the heap.  With large statically allocated objects, it's probably better to go to the heap.

**Comment by shadisharba** [comment]
Probably I'm missing sth but doesn't this solve the problem of locking when assembling the stiffness matrix?

**Comment by dbeurle** [comment]
I guess it does through the reduction declaration and I would expect it would work.  The problem with the stiffness matrix is a little more complicated because we have unstructured access to the underlying data structure.

The atomic lock method is rather primitive and more sophisticated methods (like mesh colouring) side-step the problem entirely.  However for a 'quick and dirty' solution this atomic lock should work surprisingly well.  As for removing OpenMP I'm not sure it there is a problem leaving the `#pragma omp atomic` when using a different thread library because it never calls an OpenMP library function, it just generates the instructions I'd except to see, there's just no way to handle this in c++.  If push comes to shove, we can specialise the atomic update in assembly for each platform, but it works for x86_64 so I guess there's no point in changing it just yet.

**Comment by dbeurle** [comment]
It's now possible to add
```cpp
static thread_local matrix thread_stiffness;
```
to the element level computation routines.  This provides an easy way to have local thread storage for each thread that enters a routine with a small overhead, avoiding multiple memory allocations.  I will post benchmarks, convert the rest of this over to TBB and close off the issue.

**Comment by dbeurle** [comment]
We can (somewhat dangerously maybe?) the `#pragma omp atomic` that produces the atomic instructions on x86 (would need to check other architectures) and tbb for the remaining code.  Once those assembler structures are merged together I can get rid of *most* of the OpenMP calls.

**Comment by dbeurle** [comment]
This is basically finished with the exception of the `#pragma omp atomic`.  This will likely remain until C++ standard support comes in.
