### ISSUE TITLE
compiler instruction for ubuntu 16.04 

### ISSUE THREAD

**Issue by thanhchuong8252** [dbeurle/neon#63]
g++-7
libssl https
hwloc

**Comment by dbeurle** [comment]
Do you have the commands for adding gcc-7?

**Comment by thanhchuong8252** [comment]
i save the history terminal in yesterday's afternoon, maybe it is the hint
[20180425_saved_commands.txt](https://github.com/dbeurle/neon/files/1945709/20180425_saved_commands.txt)
[20180424_saved_commands.txt](https://github.com/dbeurle/neon/files/1945710/20180424_saved_commands.txt)

**Comment by dbeurle** [comment]
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test` is probably the one.  Thanks

**Comment by dbeurle** [comment]
It's building and passing the tests on a VM with Ubuntu 16.04.  Can you please try and reproduce this using the instructions in the README.md and provide feedback?

**Comment by thanhchuong8252** [comment]
when Install dependencies through the package manager: it give some error:

_chuongnguyen@chuongnguyen:~/Documents$ sudo apt install cmake git mercurical libz-dev libcurl3-dev libvtk6-dev libtbb-dev libboost-filesystem-dev libmumps-seq-dev libopenblas-dev libarpack2-dev, libscotch-dev, hwloc libhwloc-dev libgfortran-7-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
Note, selecting 'libcurl4-openssl-dev' instead of 'libcurl3-dev'
E: Unable to locate package mercurical
E: Unable to locate package libarpack2-dev,
E: Unable to locate package libscotch-dev,_

**Comment by thanhchuong8252** [comment]
after make all -j8, it give errors:

_collect2: error: ld returned 1 exit status
tests/CMakeFiles/constitutive_test.dir/build.make:108: recipe for target 'tests/constitutive_test' failed
make[2]: *** [tests/constitutive_test] Error 1
CMakeFiles/Makefile2:1518: recipe for target 'tests/CMakeFiles/constitutive_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/constitutive_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2_

**Comment by dbeurle** [comment]
Can you run

`./tests/constitutive_test` in the build directory?

**Comment by dbeurle** [comment]
Did you manage to get this working?  There are instructions for Ubuntu 18.04 which I've tested against a clean installation.

**Comment by thanhchuong8252** [comment]
Thank Darcy, I will try to compile the code and let you know

**Comment by shadisharba** [comment]
This issue can be closed now as it is not needed anymore.
