### ISSUE TITLE
Traction boundary conditions

### ISSUE THREAD

**Issue by annierhea** [dbeurle/neon#9]
Implement handling of traction boundary conditions.

**Comment by dbeurle** [comment]
Traction boundary conditions are essentially Neumann type boundary conditions with degree of freedom attached.  We can potentially make the Neumann type generic, so it can be used later for representing scalar fluxes for one- and two-dimensional boundaries.  For this, each Neumann boundary condition would need:
* A shared pointer to material coordinates,
* Templated over an  interpolation function.

Potentially easy to implement and the shared pointer to material coordinates allows easy coupling.

**Comment by dbeurle** [comment]
This has been implemented.
