### ISSUE TITLE
SVD routines

### ISSUE THREAD

**Issue by dbeurle** [dbeurle/neon#96]
For `latin` analysis we need an SVD solver.  We can open this alongside the `linear` and `eigen` solvers.

- [ ] Create basic SVD solver and small test
- [ ] Implement factory method to select svd solvers
- [ ] Include GPU and CPU options

**Comment by dbeurle** [comment]
@shadialameddin What do you need from the routines exactly?  Left and right decompositions? Do you have plain old `matrix` datatypes? I'm writing it now :-)

Resources:
(GPU) https://docs.nvidia.com/cuda/cusolver/index.html#svd-example1
(CPU) https://eigen.tuxfamily.org/dox/group__SVD__Module.html

**Comment by dbeurle** [comment]
@shadialameddin Just hit me up with the example code in MATLAB / the known good results and I can use this as test.  If you're feeling brave you can also do it too ;)

**Comment by shadisharba** [comment]
yes, GPU implementation can be included later :)
